#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Change your keymap:
xmodmap "/home/alfons/.Xmodmap"

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
#
# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

# Iniciar aplicacions en iniciar sessió
# firefox &
# thunderbird &
# /usr/bin/conky-manager  /home/alfons/conky-manager/themes/Conky MIUI/config/miui &
# alarmclock &
conky -d -b &
# calendar.sh &
#  orage &
# glipper &
synapse &
nextcloud &
clipit &
nm-applet &
mate-power-manager &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox
# or if you want to keep a log:
# exec fluxbox -log "/home/alfons/.fluxbox/log"

setxkbmap es -variant intl& # para habilitar el teclado español y poder usar la tecla Ñ y los caracteres especiales del idioma.
